export const GAMES = [
  {id:'mlbb',slug:'mobile-legends',name:'Mobile Legends',publisher:'Moonton',category:'moba',popular:true,featured:true,status:'active',tags:['ml','mlbb'],provider:'mock',inputSchema:[{key:'userId',label:'User ID',placeholder:'123456789',required:true,validation:'digits'},{key:'zoneId',label:'Zone ID',placeholder:'1234',required:true,validation:'digits'}],products:[
    {id:'ml-12',name:'12 Diamonds',amount:12,price:3500,available:true,eta:'Referensi katalog'}, {id:'ml-28',name:'28 Diamonds',amount:28,price:8000,available:true,eta:'Referensi katalog'}, {id:'ml-56',name:'56 Diamonds',amount:56,price:16000,available:true,eta:'Referensi katalog'}, {id:'ml-85',name:'85 Diamonds',amount:85,price:23000,available:true,eta:'Referensi katalog'}, {id:'ml-169',name:'169 Diamonds',amount:169,price:46000,available:true,eta:'Referensi katalog'}, {id:'ml-220',name:'220 Diamonds',amount:220,price:60000,available:true,eta:'Referensi katalog'}]},
  {id:'ff',slug:'free-fire',name:'Free Fire',publisher:'Garena',category:'battle-royale',popular:true,featured:true,status:'active',tags:['ff'],provider:'mock',inputSchema:[{key:'userId',label:'User ID',placeholder:'123456789',required:true,validation:'digits'}],products:[
    {id:'ff-5',name:'5 Diamonds',amount:5,price:1000,available:true,eta:'Referensi katalog'}, {id:'ff-12',name:'12 Diamonds',amount:12,price:2000,available:true,eta:'Referensi katalog'}, {id:'ff-50',name:'50 Diamonds',amount:50,price:8000,available:true,eta:'Referensi katalog'}, {id:'ff-70',name:'70 Diamonds',amount:70,price:10000,available:true,eta:'Referensi katalog'}, {id:'ff-140',name:'140 Diamonds',amount:140,price:0,available:false,eta:'Menunggu harga/provider resmi'}]},
  {id:'pubgm',slug:'pubg-mobile',name:'PUBG Mobile',publisher:'KRAFTON',category:'battle-royale',popular:true,featured:false,status:'active',tags:['pubg'],provider:'mock',inputSchema:[{key:'playerId',label:'Player ID',placeholder:'123456789',required:true,validation:'digits'}],products:[
    {id:'pubg-60',name:'60 UC',amount:60,price:19200,available:true,eta:'Referensi katalog'}, {id:'pubg-325',name:'325 UC',amount:325,price:96000,available:true,eta:'Referensi katalog'}, {id:'pubg-660',name:'660 UC',amount:660,price:192000,available:true,eta:'Referensi katalog'}, {id:'pubg-1800',name:'1800 UC',amount:1800,price:480000,available:true,eta:'Referensi katalog'}]},
  {id:'hok',slug:'honor-of-kings',name:'Honor of Kings',publisher:'Level Infinite',category:'moba',popular:true,featured:false,status:'active',tags:['hok'],provider:'mock',inputSchema:[{key:'userId',label:'User ID',placeholder:'123456789',required:true,validation:'digits'}],products:[
    {id:'hok-80',name:'80 Tokens',amount:80,price:0,available:false,eta:'Menunggu harga/provider resmi'}, {id:'hok-240',name:'240 Tokens',amount:240,price:0,available:false,eta:'Menunggu harga/provider resmi'}, {id:'hok-400',name:'400 Tokens',amount:400,price:0,available:false,eta:'Menunggu harga/provider resmi'}, {id:'hok-560',name:'560 Tokens',amount:560,price:0,available:false,eta:'Menunggu harga/provider resmi'}, {id:'hok-800',name:'800 Tokens',amount:800,price:0,available:false,eta:'Menunggu harga/provider resmi'}]},
  {id:'genshin',slug:'genshin-impact',name:'Genshin Impact',publisher:'HoYoverse',category:'rpg',popular:true,featured:false,status:'active',tags:['genshin'],provider:'mock',inputSchema:[{key:'uid',label:'UID',placeholder:'123456789',required:true,validation:'digits'},{key:'server',label:'Server',placeholder:'Asia',required:true}],products:[
    {id:'gi-60',name:'60 Genesis Crystals',amount:60,price:0,available:false,eta:'Menunggu harga/provider resmi'}, {id:'gi-300',name:'300 + 30 Genesis Crystals',amount:330,price:0,available:false,eta:'Menunggu harga/provider resmi'}, {id:'gi-980',name:'980 + 110 Genesis Crystals',amount:1090,price:0,available:false,eta:'Menunggu harga/provider resmi'}, {id:'gi-1980',name:'1980 + 260 Genesis Crystals',amount:2240,price:0,available:false,eta:'Menunggu harga/provider resmi'}, {id:'gi-3280',name:'3280 + 600 Genesis Crystals',amount:3880,price:0,available:false,eta:'Menunggu harga/provider resmi'}, {id:'gi-6480',name:'6480 + 1600 Genesis Crystals',amount:8080,price:0,available:false,eta:'Menunggu harga/provider resmi'}, {id:'gi-8080',name:'8080 Genesis Crystals',amount:8080,price:0,available:false,eta:'Menunggu harga/provider resmi'}]},
  {id:'valorant',slug:'valorant',name:'Valorant',publisher:'Riot Games',category:'voucher',popular:true,featured:false,status:'active',tags:['valo'],provider:'mock',inputSchema:[{key:'riotId',label:'Riot ID',placeholder:'Nama#Tag',required:true}],products:[
    {id:'vp-125',name:'125 VP',amount:125,price:0,available:false,eta:'Menunggu harga/provider resmi'}, {id:'vp-420',name:'420 VP',amount:420,price:0,available:false,eta:'Menunggu harga/provider resmi'}, {id:'vp-700',name:'700 VP',amount:700,price:0,available:false,eta:'Menunggu harga/provider resmi'}, {id:'vp-1375',name:'1375 VP',amount:1375,price:0,available:false,eta:'Menunggu harga/provider resmi'}, {id:'vp-2400',name:'2400 VP',amount:2400,price:0,available:false,eta:'Menunggu harga/provider resmi'}, {id:'vp-3650',name:'3650 VP',amount:3650,price:0,available:false,eta:'Menunggu harga/provider resmi'}]},
  {id:'roblox',slug:'roblox',name:'Roblox',publisher:'Roblox',category:'voucher',popular:false,featured:false,status:'active',tags:['robux'],provider:'mock',inputSchema:[{key:'username',label:'Username',placeholder:'Username',required:true}],products:[
    {id:'rbx-80',name:'80 Robux',amount:80,price:0,available:false,eta:'Menunggu harga/provider resmi'}, {id:'rbx-400',name:'400 Robux',amount:400,price:0,available:false,eta:'Menunggu harga/provider resmi'}, {id:'rbx-800',name:'800 Robux',amount:800,price:0,available:false,eta:'Menunggu harga/provider resmi'}, {id:'rbx-1700',name:'1700 Robux',amount:1700,price:0,available:false,eta:'Menunggu harga/provider resmi'}, {id:'rbx-4500',name:'4500 Robux',amount:4500,price:0,available:false,eta:'Menunggu harga/provider resmi'}, {id:'rbx-10000',name:'10000 Robux',amount:10000,price:0,available:false,eta:'Menunggu harga/provider resmi'}]},
  {id:'steam',slug:'steam-wallet',name:'Steam Wallet',publisher:'Valve',category:'voucher',popular:false,featured:true,status:'active',tags:['steam'],provider:'mock',inputSchema:[{key:'email',label:'Email akun Steam',placeholder:'email@example.com',required:true}],products:[
    {id:'steam-12',name:'Rp 12.000',amount:12000,price:0,available:false,eta:'Menunggu harga/provider resmi'}, {id:'steam-20',name:'Rp 20.000',amount:20000,price:0,available:false,eta:'Menunggu harga/provider resmi'}, {id:'steam-45',name:'Rp 45.000',amount:45000,price:0,available:false,eta:'Menunggu harga/provider resmi'}, {id:'steam-60',name:'Rp 60.000',amount:60000,price:0,available:false,eta:'Menunggu harga/provider resmi'}, {id:'steam-90',name:'Rp 90.000',amount:90000,price:0,available:false,eta:'Menunggu harga/provider resmi'}, {id:'steam-120',name:'Rp 120.000',amount:120000,price:0,available:false,eta:'Menunggu harga/provider resmi'}, {id:'steam-250',name:'Rp 250.000',amount:250000,price:0,available:false,eta:'Menunggu harga/provider resmi'}, {id:'steam-400',name:'Rp 400.000',amount:400000,price:0,available:false,eta:'Menunggu harga/provider resmi'}, {id:'steam-500',name:'Rp 500.000',amount:500000,price:0,available:false,eta:'Menunggu harga/provider resmi'}, {id:'steam-1000',name:'Rp 1.000.000',amount:1000000,price:0,available:false,eta:'Menunggu harga/provider resmi'}]}
];

export const DIGITAL_PRODUCTS = [
 {id:'pulsa',slug:'pulsa',name:'Pulsa',icon:'☎',description:'Isi ulang pulsa; harga final mengikuti provider PPOB aktif.',category:'telekomunikasi',fields:[{key:'phone',label:'Nomor HP',placeholder:'08xxxxxxxxxx',required:true,validation:'phone'}],products:[{id:'pulsa-10',name:'Pulsa Rp10.000',faceValue:10000},{id:'pulsa-25',name:'Pulsa Rp25.000',faceValue:25000},{id:'pulsa-50',name:'Pulsa Rp50.000',faceValue:50000}]},
 {id:'data',slug:'paket-data',name:'Paket Data',icon:'⌁',description:'Paket internet; nominal dan harga final berasal dari provider.',category:'telekomunikasi',fields:[{key:'phone',label:'Nomor HP',placeholder:'08xxxxxxxxxx',required:true,validation:'phone'}],products:[{id:'data-5',name:'Paket Data 5 GB',faceValue:0,available:false},{id:'data-10',name:'Paket Data 10 GB',faceValue:0,available:false}]},
 {id:'ewallet',slug:'ewallet',name:'Top Up E-Wallet',icon:'◉',description:'Top up e-wallet transparan. Rincian biaya dan pajak ditampilkan sebelum pembayaran; estimasi saldo diterima dihitung secara transparan.',category:'ewallet',fields:[{key:'wallet',label:'E-Wallet',placeholder:'Pilih e-wallet',required:true,validation:'select'},{key:'account',label:'Nomor HP / ID Tujuan',placeholder:'Masukkan nomor tujuan',required:true,validation:'phone'}],products:[100,150,200,250,300,350,400,450,500,550,600,650,700,750,800,850,900,950,1000].map(k=>({id:`ewallet-${k}`,name:`Saldo Rp${new Intl.NumberFormat('id-ID').format(k*1000)}`,faceValue:k*1000})).concat([{id:'ewallet-custom',name:'Nominal lainnya',faceValue:0,custom:true}])},
 {id:'pln',slug:'pln-token',name:'Token PLN',icon:'ϟ',description:'Nominal token dan perlakuan pajak mengikuti biller/provider.',category:'tagihan',fields:[{key:'customerNumber',label:'ID Pelanggan / No Meter',placeholder:'Masukkan nomor pelanggan',required:true,validation:'digits'}],products:[{id:'pln-20',name:'Token Rp20.000',faceValue:20000},{id:'pln-50',name:'Token Rp50.000',faceValue:50000},{id:'pln-100',name:'Token Rp100.000',faceValue:100000}]},
 {id:'pdam',slug:'pdam',name:'PDAM',icon:'≈',description:'Cek tagihan aktual terlebih dahulu; nominal berasal dari biller.',category:'tagihan',inquiryRequired:true,fields:[{key:'customerNumber',label:'Nomor Pelanggan',placeholder:'Masukkan nomor pelanggan',required:true,validation:'digits'}],products:[{id:'pdam-bill',name:'Cek & Bayar Tagihan',faceValue:0}]},
 {id:'bpjs',slug:'bpjs',name:'BPJS',icon:'✚',description:'Cek tagihan peserta terlebih dahulu; nominal berasal dari biller.',category:'tagihan',inquiryRequired:true,fields:[{key:'customerNumber',label:'Nomor Peserta',placeholder:'Masukkan nomor peserta',required:true,validation:'digits'}],products:[{id:'bpjs-bill',name:'Cek & Bayar Tagihan',faceValue:0}]},
 {id:'voucher',slug:'voucher',name:'Voucher Digital',icon:'▣',description:'Voucher dengan harga final dari provider/distributor aktif.',category:'voucher',fields:[{key:'email',label:'Email penerima',placeholder:'email@contoh.com',required:true,validation:'email'}],products:[{id:'voucher-steam-8',name:'Steam Wallet Rp8.000',faceValue:8000,available:false},{id:'voucher-steam-12',name:'Steam Wallet Rp12.000',faceValue:12000,available:false},{id:'voucher-google',name:'Google Play',faceValue:0,available:false}]},
 {id:'transfer',slug:'transfer',name:'Transfer Bank / E-Wallet',icon:'→',description:'Disbursement membutuhkan provider payout dan kontrol kepatuhan.',category:'transfer',disabled:true,fields:[{key:'destination',label:'Tujuan',placeholder:'Nomor rekening / e-wallet',required:true}],products:[{id:'transfer-basic',name:'Transfer',faceValue:0,available:false}]}
];

export const GAME_PRODUCT_MAP = Object.fromEntries(GAMES.flatMap(g=>g.products.map(p=>[p.id,{...p,gameId:g.id,name:p.name,price:Number(p.price||0)}])));
export const DIGITAL_PRODUCT_MAP = Object.fromEntries(DIGITAL_PRODUCTS.flatMap(s=>s.products.map(p=>[p.id,{...p,serviceId:s.id,name:p.name,faceValue:Number(p.faceValue||0)}])));
